### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by Brandoncheaa** [bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models#3]
Hello I am trying to run your code for sample_trials.py however I am getting an error where there is no module named generative.

**Comment by Brandoncheaa** [comment]
Seems to be referring to this line: 
"from generative.inferers import DiffusionInferer
from generative.networks.schedulers import DDIMScheduler"

**Comment by Brandoncheaa** [comment]
or could you possibly provide the specific script to generate the samples, the files are pretty dense are somewhat hard to navigate around. Thank you

**Comment by bruAristimunha** [comment]
Hi @Brandoncheaa,

Could you let me know if you installed the requirements.txt?

```bash
pip install -r requirements.txt
```
This is related to issue #2. The generative dependencies are from [monai-generative](https://github.com/Project-MONAI/GenerativeModels).

**Comment by bruAristimunha** [comment]
Can you clarify what is confusing to you in the code?

**Comment by Brandoncheaa** [comment]
I am running "python sample_trials.py" to generate samples from the diffusion model, and am running into that first issue. I have installed all the requirements in requirements.txt

**Comment by Brandoncheaa** [comment]
This is now the error I am getting after re-installing requirements and manually installing lpips, 
"MONAI version: 1.3.1
Numpy version: 1.26.4
Pytorch version: 2.3.0+cu121
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 96bfda00c6bd290297f5e3514ea227c6be4d08b4
MONAI __file__: /cluster/research-groups/ramasubramanian/workspace/<username>/miniconda/envs/LTGAN/lib/python3.12/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: 0.23.2
scipy version: 1.13.1
Pillow version: 10.3.0
Tensorboard version: 2.16.2
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.18.0+cu121
tqdm version: 4.66.4
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 2.2.2
einops version: 0.8.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.13.0
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.
clearml version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Traceback (most recent call last):
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/project/sample_synthetic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/academic/projects/ASCS/env/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/src/sample_trials.py", line 200, in <module>
    main(args)
  File "/cluster/academic/projects/ASCS/env/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/src/sample_trials.py", line 88, in main
    Path(args.output_dir).mkdir(exist_ok=True, parents=True)
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/project'"

Do you believe this is a cluster related issue or with access to your files

**Comment by Brandoncheaa** [comment]
I'm running sample_trials.py, however im getting issues with it making directories in folders outside of the project folder. This is the specific error, "MONAI version: 1.3.1
Numpy version: 1.26.4
Pytorch version: 2.3.0+cu121
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 96bfda00c6bd290297f5e3514ea227c6be4d08b4
MONAI __file__: /cluster/research-groups/ramasubramanian/workspace/<username>/miniconda/envs/LTGAN/lib/python3.12/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: NOT INSTALLED or UNKNOWN VERSION.
ITK version: NOT INSTALLED or UNKNOWN VERSION.
Nibabel version: NOT INSTALLED or UNKNOWN VERSION.
scikit-image version: 0.23.2
scipy version: 1.13.1
Pillow version: 10.3.0
Tensorboard version: 2.16.2
gdown version: NOT INSTALLED or UNKNOWN VERSION.
TorchVision version: 0.18.0+cu121
tqdm version: 4.66.4
lmdb version: NOT INSTALLED or UNKNOWN VERSION.
psutil version: NOT INSTALLED or UNKNOWN VERSION.
pandas version: 2.2.2
einops version: 0.8.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.13.0
pynrrd version: NOT INSTALLED or UNKNOWN VERSION.
clearml version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Traceback (most recent call last):
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/project/sample_synthetic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/academic/projects/ASCS/env/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/src/sample_trials.py", line 200, in <module>
    main(args)
  File "/cluster/academic/projects/ASCS/env/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/src/sample_trials.py", line 88, in main
    Path(args.output_dir).mkdir(exist_ok=True, parents=True)
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1315, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/LTGAN/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/project'"

I'm confused where the file path is for pathlib so maybe I could reroute where things are being saved but I can't find it.

**Comment by Brandoncheaa** [comment]
I've installed all necessary requirements from the requirements.txt as well as manually installing lpips.

**Comment by Brandoncheaa** [comment]
I believe the issues I am having are from the sample_trials.py file, it seems that the file paths that it is directed too are having an issue. I am trying to directly have it read from my project folders by specifying the path, i.e. 
"parser.add_argument("--output_dir", help="Path to save the .pth file of the diffusion model.",
                        # default = "/project/output")
                        default="/cluster/research-groups/ramasubramanian/workspace/cheab/output")"

however for the other paths:
"parser.add_argument("--best_model_path",
                        help="Path to the .pth model from the stage1.",
                        default="/project/outputs/aekl_eeg_{}_{}_{}")
                        #aekl_eeg_no-spectral_shh
![Screenshot 2024-05-23 212454](https://github.com/bruAristimunha/Synthetic-Sleep-EEG-Signal-Generation-using-Latent-Diffusion-Models/assets/1521779/e77fd3ce-5473-4507-a15c-33f1d33c0ffc)
s1_1"
I'm not quite sure what I should be directing them too

**Comment by Brandoncheaa** [comment]
Could you provide the direct script that you used to run sample_trials.py?

**Comment by Brandoncheaa** [comment]
I believe the issues are with the default paths set in the parser arguments within sample_trials.py, would appreciate any feedback
